config/routes.rb
Rails.application.routes.draw do
  namespace :my do
    get 'product_categories/index'
  end

  namespace :my do
    get 'products/index'
  end

  get 'products/index'

  get 'product_categories/index'

  # get 'homes/index'

  namespace :admin do
    get 'stock_categories/index'
  end

  namespace :admin do
    get 'stocks/index'
  end

  devise_for :users, controllers: { sessions: 'users/sessions' }

  root "homes#index"

  namespace :admin do
    get 'users/dashboard'
    resources :branches
    resources :stock_categories
    resources :stocks
    resources :users
    resources :companies
  end

  namespace :my do
    get 'users/dashboard'
    resources :companies
    resources :product_categories
    resources :products
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  include ApplicationHelper
  self.abstract_class = true
end

app/models/branch.rb
class Branch < ApplicationRecord
  belongs_to :company
  has_many :stocks
  has_many :stock_categories
  has_many :employees

  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 255 }
  validates :email, presence: true, uniqueness: true, length: { maximum: 255 }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :employees
  has_many :branches
  enum status: { pending: APP::PENDING, active: APP::ACTIVE, inactive: APP::INACTIVE, banned: APP::BANNED }
  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 255 }
  validates :email, allow_blank: true, length: { maximum: 255 }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :branch
  belongs_to :company
  validates :email, allow_blank: true, length: { maximum: 255 }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validate :valid_phones

  def valid_phones
    validate_phones_by_comma(phones)
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :stock
  belongs_to :product_category
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :stock_category
  belongs_to :branch

  enum status: { pending: APP::PENDING, active: APP::ACTIVE, inactive: APP::INACTIVE, deleted: APP::DELETED, banned: APP::BANNED }
  
  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 255 }
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :sale_price, presence: true, numericality: { greater_than_or_equal_to: :price }

  before_save :check_alerted_quantity

  def check_alerted_quantity
    self.alerted = (self.qty <= self.alert_qty) ? true : false
  end
end

app/models/stock_category.rb
class StockCategory < ApplicationRecord
  belongs_to :branch
  has_many :stocks

  validates :name, presence: true, uniqueness: { scope: :branch_id, case_sensitive: false }, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :role
  has_many :companies
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # before_validation :set_default_role, on: :create

  enum status: { pending: APP::PENDING, active: APP::ACTIVE, inactive: APP::INACTIVE, banned: APP::BANNED }
  enum gender: { male: APP::MALE, female: APP::FEMALE, other: APP::OTHER }
  before_save :concatenate_name

  def concatenate_name
    self.name = "#{firstname}#{lastname}"
  end

  private

  # def set_default_role
  #   self.role = Role.find_by_name(APP::ROLE_USER)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  include DeviseHelper

  protect_from_forgery with: :exception

  protected
  
  def after_sign_in_path_for(resource)
    redirect_path = root_path
    if is_admin_superadmin?(current_user)
      redirect_path = admin_users_dashboard_path
    else
      redirect_path = my_users_dashboard_path
    end
    
    request.env['omniauth.origin'] || stored_location_for(resource) || redirect_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/helpers/admin/branches_helper.rb
module Admin::BranchesHelper
end

app/helpers/admin/stocks_helper.rb
module Admin::StocksHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin_layout
    'admin'
  end

  def my_layout
    'my'
  end

  def is_superadmin? obj
    return obj.role == Role.find_by_name(APP::ROLE_SUPERADMIN)
  end

  def is_admin? obj
    return obj.role == Role.find_by_name(APP::ROLE_ADMIN)
  end

  def is_editor? obj
    return obj.role == Role.find_by_name(APP::ROLE_EDITOR)
  end

  def is_admin_superadmin? obj
    is_admin?(obj) or is_superadmin?(obj)
  end

  def is_editor_admin_superadmin? obj
    is_admin?(obj) or is_editor?(obj) or is_superadmin?(obj)
  end

  def is_number? string
    true if Float(string) rescue false
  end

  def authentication_validation
    unless is_admin_superadmin?(current_user)
      flash[:warning] = "No permission!"
      redirect_to root_path
    end
  end

  def validate_phones_by_comma(phones)
    if phones.present?
      phones.split(',').map { |phone|
        replacements = ['-', '+', '(', ')', ' ']
        replacements.each {|replacemnt| phone = phone.gsub(replacemnt, '')}
        # p phone
        unless is_number?(phone)
          errors.add(:phones, ", #{phone}, is not a number!")
        end

        if phone.length < 9
          errors.add(:phones, ", #{phone}, is too short!")
        end

        if phone.length > 13
          errors.add(:phones, ", #{phone}, is too long! ")
        end
      }
    end
  end

  def is_user_have_companies? obj
    @user_companies = Company.find_by("user_id = #{obj}")
    return @user_companies.blank?
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/my/companies_helper.rb
module My::CompaniesHelper
end

app/helpers/my/products_helper.rb
module My::ProductsHelper
end

app/helpers/my/users_helper.rb
module My::UsersHelper
end

app/views/layouts/admin.html.slim
doctype html
html
  head
    - unless display_meta_tags.blank?
      = display_meta_tags
    - else
      title = APP::NAME
    = csrf_meta_tags

    / <!-- Animation library for notifications   -->
    / = stylesheet_link_tag    '/site/assets/css/animate.min.css', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body id="#{params[:controller].gsub(/\//, '_') + '_' + params[:action]}" data-controller=params[:controller].gsub(/\//, '_') data-action=params[:action] class="admin-layout hold-transition login-page" data-url="#{request.base_url}"
    .wrapper.clearfix
      = render "share/sidebar"
      .main-wrapper
        = render 'share/header'
        .content
          = render 'share/flash_message'
          = yield
        = render 'share/footer'

app/views/layouts/application.html.slim
doctype html
html
  head
    = csrf_meta_tags
    - unless display_meta_tags.blank?
      = display_meta_tags
    - else
      title = APP::NAME
      
    = stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body id="#{params[:controller].gsub(/\//, '_') + '_' + params[:action]}" data-controller=params[:controller].gsub(/\//, '_') data-action=params[:action] class="admin-layout hold-transition login-page" data-url="#{request.base_url}"
    = yield

app/views/layouts/my.html.slim
doctype html
html
  head
    - unless display_meta_tags.blank?
      = display_meta_tags
    - else
      title = APP::NAME
    = csrf_meta_tags

    / <!-- Animation library for notifications   -->
    / = stylesheet_link_tag    '/site/assets/css/animate.min.css', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body id="#{params[:controller].gsub(/\//, '_') + '_' + params[:action]}" data-controller=params[:controller].gsub(/\//, '_') data-action=params[:action] class="admin-layout hold-transition login-page" data-url="#{request.base_url}"
    .wrapper.clearfix
      = render "share/sidebar"
      .main-wrapper
        = render 'share/header'
        .content
          = render 'share/flash_message'
          = yield
        = render 'share/footer'

app/views/share/_error_messages.html.slim
- if @error_messages && @error_messages.errors.any?
  .alert.alert-danger.alert-dismissible role="alert"
    button type="button" class="close" data-dismiss="alert" aria-label="Close"
      span aria-hidden="true" &times
    strong Please complete this information!
    ul
      - @error_messages.errors.full_messages.each do |msg|
        li = msg

app/views/share/_flash_message.html.slim
= flash_messages(:close)

app/views/share/_footer.html.slim
.footer-be.text-right
  p.copyright
    | &copy; 
    = Date.today.year
    | , made with 
    i.fa.fa-heart.fa-danger
    |  by Kheang

app/views/share/_header.html.slim
- ctrl_action = params[:controller].gsub(/\//, '_') + '_' + params[:action]
- ctrl_param = params[:controller].gsub(/\//, '_')
nav.navbar.navbar-default.navbar-main
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="#"
        - if ctrl_param == 'admin_users' and ctrl_action != 'admin_users_index'
          = APP::DASHBOARD
        - elsif ctrl_param == 'admin_branches'
          = APP::BRANCHES
        - elsif ctrl_param == 'admin_stock_categories'
          = APP::STOCK_CATEGORIES
        - elsif ctrl_param == 'admin_stocks'
          = APP::STOCKS
        - elsif ctrl_param == 'admin_users' or ctrl_action == 'admin_users_index'
          = APP::USERS
        - elsif ctrl_param == 'admin_companies' or ctrl_action == 'admin_companies_index'
          = APP::COMPANIES
        - else
          = ""
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - unless @alerted_count.blank? or @alerted_count == 0 or 'admin_stocks_index'.include?(ctrl_action) ? false : true
          li.dropdown
            a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
              span.alerted-count = @alerted_count
              i.fa.fa-bell
              span.caret
            ul.dropdown-menu.card.card-navbar.custom-pad
              - if @alerted_count
                - i = 0
                - for alr in @alerted_stock
                  li
                    = link_to "<strong>#{alr.name}</strong> is running out of stock!".html_safe, edit_admin_stock_path(alr.id), class: "alert-link"
                    - i += 1
                    - unless i > (@alerted_count - 1)
                      hr.seperator
        li.padd
          - if current_user
            strong.username = current_user.name
        li.dropdown
          a.dropdown-toggle.nav-user aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
            i.fa.fa-user.fa-nav
          ul.dropdown-menu.card.card-navbar
            li
              - if current_user
                a href="#" = current_user.role.name.capitalize
              - else
                a href="#"  Admin
            li
              a href="#"  Edit
            li
              = link_to "Sign Out", destroy_user_session_path, :method => :delete
      / form.navbar-form.navbar-right
      /   .input-group
      /     input.form-control placeholder="Search" type="text" /
      /     span.input-group-btn
      /       button.btn.btn-default type="submit"
      /         i.fa.fa-search

app/views/share/_sidebar.html.slim
- ctrl_action = params[:controller].gsub(/\//, '_') + '_' + params[:action]
aside#mySidenav.sidebar
  .sidebar-header.text-center
    h3.site-name = APP::NAME
  ul.nav.nav-menu

    / - if current_user.role.name == APP::ROLE_SUPERADMIN
    - pa_controller = params[:controller].split('/')
    - if pa_controller[0] == APP::ADMIN
      li class="#{(['admin_users_dashboard'].include?(ctrl_action)) ? "active": ""}"
        = link_to admin_users_dashboard_path
          i.fa.fa-tachometer
          | Dashboard
      li class="#{(['admin_users_index', 'admin_users_new', 'admin_users_create', 'admin_users_edit', 'admin_users_show'].include?(ctrl_action)) ? "active": ""}"
        = link_to admin_users_path
          i.fa.fa-home
          | Users
      / li class="#{(['admin_branches_index', 'admin_branches_new', 'admin_branches_create', 'admin_branches_edit'].include?(ctrl_action)) ? "active": ""}"
      /   = link_to admin_branches_path
      /     i.fa.fa-home
      /     | Branch
      li class="#{(['admin_companies_index', 'admin_companies_new', 'admin_stock_categories_create', 'admin_stock_categories_delete'].include?(ctrl_action)) ? "active": ""}"
        = link_to admin_companies_path
          i.fa.fa-list-alt
          | Companies
      - unless is_user_have_companies? current_user.id
        li class="#{(['my_stock_categories_index', 'my_stock_categories_edit', 'my_stock_categories_create', 'my_stock_categories_delete'].include?(ctrl_action)) ? "active": ""}"
          = link_to admin_stock_categories_path
            i.fa.fa-list-alt
            | Stock Category
        li class="#{(['admin_stocks_index', 'admin_stocks_show', 'admin_stocks_edit'].include?(ctrl_action)) ? "active": ""}"
          = link_to admin_stocks_path
            i.fa.fa-table
            | Stock

    - elsif pa_controller[0] == APP::MY
      li class="#{(['my_users_dashboard'].include?(ctrl_action)) ? "active": ""}"
        = link_to admin_users_dashboard_path
          i.fa.fa-tachometer
          | Dashboard
      li class="#{(['my_stock_categories_index', 'my_stock_categories_edit', 'my_stock_categories_create', 'my_stock_categories_delete'].include?(ctrl_action)) ? "active": ""}"
        = link_to my_product_categories_path
          i.fa.fa-list-alt
          | Product Categories
      li class="#{(['admin_stocks_index', 'admin_stocks_show', 'admin_stocks_edit'].include?(ctrl_action)) ? "active": ""}"
        = link_to my_products_path
          i.fa.fa-table
          | Products
      / li class="#{(['my_stock_categories_index', 'my_stock_categories_edit', 'my_stock_categories_create', 'my_stock_categories_delete'].include?(ctrl_action)) ? "active": ""}"
      /   = link_to admin_stock_categories_path
      /     i.fa.fa-list-alt
      /     | Stock Category
      / li class="#{(['admin_stocks_index', 'admin_stocks_show', 'admin_stocks_edit'].include?(ctrl_action)) ? "active": ""}"
      /   = link_to admin_stocks_path
      /     i.fa.fa-table
      /     | Stock