config/routes.rb
Rails.application.routes.draw do
  namespace :my do
    get 'product_categories/index'
  end

  namespace :my do
    get 'products/index'
  end

  get 'products/index'

  get 'product_categories/index'

  # get 'homes/index'

  namespace :admin do
    get 'stock_categories/index'
  end

  namespace :admin do
    get 'stocks/index'
  end

  devise_for :users, controllers: { sessions: 'users/sessions' }

  root "homes#index"

  namespace :admin do
    get 'users/dashboard'
    resources :branches
    resources :stock_categories
    resources :stocks
    resources :users
    resources :companies
  end

  namespace :my do
    get 'users/dashboard'
    resources :companies
    resources :product_categories
    resources :products
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :employees
  has_many :branches
  enum status: { pending: APP::PENDING, active: APP::ACTIVE, inactive: APP::INACTIVE, banned: APP::BANNED }
  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 255 }
  validates :email, allow_blank: true, length: { maximum: 255 }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :authentication_validation
  layout :admin_layout

  def index
    @companies = Company.where(user_id: current_user.id)
  end

  def new
    @users = User.all
    @company = Company.new
    @company_form_url = admin_companies_path
  end

  def create
    @users = User.all
    @company = Company.new(company_params)
    @company_form_url = admin_companies_path

    # if save record success
    if @company.save
      flash[:success] = "company #{@company.name} had been created successfully."
      redirect_to admin_companies_path
      return
    else
      @error_messages = @company
      render 'new'
      return
    end
  end

  def edit
    # find record with an id params
    @users = User.all
    @companies = Company.all
    @company = Company.find_by_id(params[:id])
    @company_user_id = Company.find_by(user_id: current_user.id)

    unless @company_user_id != current_user.id
      flash[:warning] = "You're not a company's owner!"
      redirect_to admin_users_dashboard_path
      return
    end

    unless @company
      flash[:error] = "Company not found with an id ##{params[:id]}"
      redirect_to admin_companies_path
      return
    end

    @company_method = "PATCH"
    @company_form_url = admin_company_path(@company.id)
  end

  # update department
  def update
    # find record with an id params
    @users = User.all
    @company = Company.find_by_id(params[:id])

    unless @company
      flash[:error] = "Branch not found with an id ##{params[:id]}"
      redirect_to admin_companies_path
      return
    end

    @company_method = "PATCH"
    @company_form_url = admin_company_path(@company.id)

    # if update record success
    if @company.update(company_params)
      flash[:success] = "Company #{@company.name} had been updated successfully."
      redirect_to admin_companies_path
      return
    else
      @error_messages = @company
      render 'edit'
      return
    end
  end

  def show
    # find record with an id params
    @company = Company.find_by_id(params[:id])

    unless @company
      flash[:error] = "Company not found with an id ##{params[:id]}"
      redirect_to admin_companies_path
      return
    end
    
    @branches = Branch.where(company_id: @company.id)
  end

  def destroy
    # find record with an id params
    @company = Company.find_by_id(params[:id])

    unless @company
      flash[:error] = "Company not found with an id ##{params[:id]}"
      redirect_to admin_companies_path
      return
    end

    @company.destroy
    flash[:success] = "Company with an id ##{params[:id]} has been deleted"
    redirect_to admin_companies_path

  end
  private

  def company_params
    params.require(:company).permit(:name, :website, :email, :phone, :address, :description, :status, :user_id)
  end
end

app/controllers/my/companies_controller.rb
class My::CompaniesController < ApplicationController
  before_action :authenticate_user!
  layout :my_layout

  def index
    @companies = Company.all
  end
end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/helpers/my/companies_helper.rb
module My::CompaniesHelper
end

app/views/admin/companies/_branch-list.html.slim
- unless @branch.blank?
  .block-grid-item
    a.block-inner.card href="#{admin_branch_path(@branch.id)}"
      .block-description.card-body
        h4.block-title = @branch.name
- else
  .alert.alert-warning.alert-dismissible role="alert"
    button type="button" class="close" data-dismiss="alert" aria-label="Close"
      span aria-hidden="true" &times
    strong Your company doesn't have any braches yet!

app/views/admin/companies/_form.html.slim
.row
  .col-sm-5
    .card.card-tasks
      / .card-header
      .card-body
        = form_for @company, html:{method: (@company_method.blank?) ? "POST" : @company_method, class: "frm-custom" , id: "company_frm_id"}, url: @company_form_url do |f|
          #message_wrapper
            = render 'share/error_messages'
          .form-group
            = f.label :name, for: 'company_name'
            = f.text_field :name, class: 'form-control', placeholder: 'Name', autofocus: true
          .form-group
            = f.label :website, for: 'company_website'
            = f.text_field :website, class: 'form-control', placeholder: 'Website'
          .form-group
            = f.label :phone, for: 'company_phone'
            = f.text_field :phone, class: 'form-control', placeholder: 'Phone'
          .form-group
            = f.label :email, for: 'company_email'
            = f.text_field :email, class: 'form-control', placeholder: 'Email'
          .form-group
            = f.label :user, for: "company_user_id"
            = f.select(:user_id, @users.collect { |a| [a.name, a.id] }, {}, class: 'form-control')
          .form-group
            = f.label :address, for: 'company_address'
            = f.text_area :address, rows: 2, cols: 2, class: 'form-control', placeholder: 'Address'
          .form-group
            = f.label :descriptions, for: 'company_descriptions'
            = f.text_area :descriptions, rows: 2, cols: 2, class: 'form-control', placeholder: 'Description'
          .form-group
            = link_to 'Cancel', admin_branches_path, class: 'btn btn-default'
            span &nbsp;
            - if @edit_btn && @edit_btn == true
              = f.submit 'Update', class: 'btn btn-primary'
            - else
              = f.submit 'Save', class: 'btn btn-primary'

app/views/admin/companies/_list.html.slim
/ - unless @company.blank?
/     .block-grid-item
/       a.block-inner.card href="#{edit_admin_company_path(@company.id)}"
/         .block-description.card-body
/           h4.block-title = @company.name

tr
  td = @i += 1
  td = @company.name
  td = @company.user.name
  td = @company.email
  td = @company.phone
  td = @company.website
  td
    ul class="list-inline"
      li = link_to "Edit", edit_admin_company_path(@company.id)
      li = link_to "Show", admin_company_path(@company.id)
      li = link_to "Delete", admin_company_path(@company.id), method: :delete, data: { confirm: 'Are you sure?' }

app/views/admin/companies/edit.html.slim
- @edit_btn = true
= render 'form'

app/views/admin/companies/index.html.slim
/ .row
/   .col-sm-12
/     - unless @companies.blank?
/       .section-wrapper
/         .block-grid-xs-2.block-grid-sm-4.block-grid-md-4.block-grid-lg-4
/           - for @company in @companies
/             = render 'list'
/     - else
/       .section-wrapper
/         p We don't have any companies yet!

= link_to "Add New", new_admin_company_path, :class => "btn btn-primary btn-btmar"
.row
  .col-sm-12
    .card.card-tasks
      .card-body
        - unless @companies.blank?
          table.table
            thead
              tr
                th #
                th Name
                th Owner
                th Email
                th Phone
                th Website
                th Action
            tbody
              - @i = 0
              - for @company in @companies
                = render 'list'
        - else
          .section-wrapper
            p We don't have any companies yet!

app/views/admin/companies/new.html.slim
= render "form"

app/views/admin/companies/show.html.slim
= link_to "Add Branch", new_admin_branch_path, :class => "btn btn-primary btn-btmar"
h4.title = @company.name
- unless @branches.blank?
  .section-wrapper
    .block-grid-xs-2.block-grid-sm-4.block-grid-md-4.block-grid-lg-4
      - for @branch in @branches
        = render 'branch-list'