config/routes.rb
Rails.application.routes.draw do
  namespace :my do
    get 'product_categories/index'
  end

  namespace :my do
    get 'products/index'
  end

  get 'products/index'

  get 'product_categories/index'

  # get 'homes/index'

  namespace :admin do
    get 'stock_categories/index'
  end

  namespace :admin do
    get 'stocks/index'
  end

  devise_for :users, controllers: { sessions: 'users/sessions' }

  root "homes#index"

  namespace :admin do
    get 'users/dashboard'
    resources :branches
    resources :stock_categories
    resources :stocks
    resources :users
    resources :companies
  end

  namespace :my do
    get 'users/dashboard'
    resources :companies
    resources :product_categories
    resources :products
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/stock_category.rb
class StockCategory < ApplicationRecord
  belongs_to :branch
  has_many :stocks

  validates :name, presence: true, uniqueness: { scope: :branch_id, case_sensitive: false }, length: { maximum: 255 }
end

app/controllers/admin/stock_categories_controller.rb
class Admin::StockCategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :authentication_validation
  layout :admin_layout

  def index
    # @branches = Branch.all
    @companies = Company.where(user_id: current_user.id)
    @branches = Branch.where(company_id: @companies.ids)
    @stock_categories = StockCategory.all
    @stock_category = StockCategory.new
    @stock_category_form_url = admin_stock_categories_path
  end

  def new
    @companies = Company.where(user_id: current_user.id)
    @branches = Branch.where(company_id: params[:company_id])
    @stock_categories = StockCategory.all
    @stock_category = StockCategory.new
    @stock_category_form_url = admin_stock_categories_path
  end


  def create
    @companies = Company.where(user_id: current_user.id)
    @branches = Branch.where(company_id: params[:company_id])
    @stock_categories = StockCategory.all
    @stock_category = StockCategory.new(stock_category_params)
    @stock_category_form_url = admin_stock_categories_path

    # if save record success
    if @stock_category.save
      flash[:success] = "Stock Category #{@stock_category.name} had been created successfully."
      redirect_to admin_stock_categories_path
      return

    else
      @error_messages = @stock_category
      render 'index'
      return
    end
  end

  def edit
    @companies = Company.where(user_id: current_user.id)
    @branches = Branch.where(company_id: params[:company_id])
    # find record with an id params
    @stock_categories = StockCategory.where(branch_id: @branches.ids)
    @stock_category = StockCategory.find_by_id(params[:id])

    @branches = Branch.all

    unless @stock_category
      flash[:error] = "Stock Category not found with an id ##{params[:id]}"
      redirect_to admin_stock_categories_path
      return
    end

    @stock_category_method = "PATCH"
    @stock_category_form_url = admin_stock_categories_path(@stock_category.id)
  end

  # update department
  def update
    @companies = Company.where(user_id: current_user.id)
    @branches = Branch.where(company_id: params[:company_id])
    # find record with an id params
    @stock_category = StockCategory.find_by_id(params[:id])

    unless @stock_category
      flash[:error] = "Stock Category not found with an id ##{params[:id]}"
      redirect_to admin_stock_categories_path
      return
    end

    @stock_category_method = "PATCH"
    @stock_category_form_url = admin_stock_categories_path(@stock_category.id)

    # if update record success
    if @stock_category.update(stock_category_params)
      flash[:success] = "Stock Category #{@stock_category.name} had been updated successfully."
      redirect_to admin_stock_categories_path
      return
    else
      @error_messages = @stock_category
      render 'edit'
      return
    end
  end

  # def show
  #   # find record with an id params
  #   @stock_category = StockCategory.find_by_id(params[:id])
  #   @stock_categories = StockCategory.where("id = ?", params[:id])

  #   unless @stock_category
  #     flash[:error] = "Stock Category not found with an id ##{params[:id]}"
  #     redirect_to admin_stock_categories_path
  #     return
  #   end
  # end

  def destroy
    # find record with an id params
    @stock_category = StockCategory.find_by_id(params[:id])

    unless @stock_category
      flash[:error] = "Stock Category not found with an id ##{params[:id]}"
      redirect_to admin_stock_categories_path
      return
    end

    @stock_category.destroy
    flash[:success] = "Stock Category with an id ##{params[:id]} has been deleted"
    redirect_to admin_stock_categories_path

  end

  private

  def stock_category_params
    params.require(:stock_category).permit(:name, :description, :branch_id, :company_id)
  end
end

app/helpers/admin/stock_categories_helper.rb
module Admin::StockCategoriesHelper
end

app/views/admin/stock_categories/_form.html.slim
= form_for @stock_category, html:{method: (@stock_category_method.blank?) ? "POST" : @stock_category_method, class: "frm-custom" , id: "stock_category_frm_id"}, url: @stock_category_form_url do |f|
  #message_wrapper
    = render 'share/error_messages'
  .form-group
    = f.label :name, for: 'branch_name'
    = f.text_field :name, class: 'form-control', placeholder: 'Name', autofocus: true
  .form-group
    = f.label :company, for: "company_id"
    = f.select(:company_id, @companies.all.collect { |a| [a.name, a.id] }, {}, class: 'form-control')
  .form-group
    = f.label :branch, for: "branch_id"
    = f.select(:branch_id, @branches.all.collect { |a| [a.name, a.id] }, {}, class: 'form-control')
  .form-group
    = f.label :description, for: 'branch_description'
    = f.text_area :description, rows: 2, cols: 2, class: 'form-control', placeholder: 'Description'
  .form-group
    = link_to 'Cancel', admin_stock_categories_path, class: 'btn btn-default'
    span &nbsp;
    - if @edit_btn && @edit_btn == true
      = f.submit 'Update', class: 'btn btn-primary'
    - else
      = f.submit 'Save', class: 'btn btn-primary'

app/views/admin/stock_categories/_list.html.slim
table.table
  thead
    tr
      th #
      th Name
      th Branch
      th Action
  tbody
    - i = 0
    - for @stc in @stock_categories
      tr
        td = i += 1
        td = @stc.name
        td = @stc.branch.name
        td
          ul.list-inline
            li = link_to "Edit", edit_admin_stock_category_path(@stc.id)
            li = link_to "Delete", admin_stock_category_path(@stc.id), method: 'DELETE', data: { confirm: 'Are you sure?' }

app/views/admin/stock_categories/edit.html.slim
- @edit_btn = true
.row
  .col-sm-5
    .card.card-tasks
      / .card-header
      .card-body
        = render 'form'
  .col-sm-7
    .card.card-tasks
      / .card-header
      .card-body
        = render 'list'

app/views/admin/stock_categories/index.html.slim
.row
  .col-sm-5
    .card.card-tasks
      / .card-header
      .card-body
        = render 'form'
  .col-sm-7
    .card.card-tasks
      / .card-header
      .card-body
        = render 'list'