config/routes.rb
Rails.application.routes.draw do
  namespace :my do
    get 'product_categories/index'
  end

  namespace :my do
    get 'products/index'
  end

  get 'products/index'

  get 'product_categories/index'

  # get 'homes/index'

  namespace :admin do
    get 'stock_categories/index'
  end

  namespace :admin do
    get 'stocks/index'
  end

  devise_for :users, controllers: { sessions: 'users/sessions' }

  root "homes#index"

  namespace :admin do
    get 'users/dashboard'
    resources :branches
    resources :stock_categories
    resources :stocks
    resources :users
    resources :companies
  end

  namespace :my do
    get 'users/dashboard'
    resources :companies
    resources :product_categories
    resources :products
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :role
  has_many :companies
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # before_validation :set_default_role, on: :create

  enum status: { pending: APP::PENDING, active: APP::ACTIVE, inactive: APP::INACTIVE, banned: APP::BANNED }
  enum gender: { male: APP::MALE, female: APP::FEMALE, other: APP::OTHER }
  before_save :concatenate_name

  def concatenate_name
    self.name = "#{firstname}#{lastname}"
  end

  private

  # def set_default_role
  #   self.role = Role.find_by_name(APP::ROLE_USER)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :authentication_validation
  layout :admin_layout

  def dashboard
    @alerted_stock = Stock.where(alerted: true, status: APP::ACTIVE)
    @alerted_count = @alerted_stock.count
  end

  def index
    @users = User.order('created_at')
  end

  def new
    @roles = Role.order('id DESC')
    @user = User.new
    @user_form_url = admin_users_path
  end

  def create
    @roles = Role.where('name IS NOT "superadmin"')
    @user = User.new(user_params)
    @user_form_url = admin_users_path

    # if save record success
    if @user.save
      flash[:success] = "User #{@user.name} had been created successfully."
      redirect_to admin_users_path
      return
    else
      @error_messages = @user
      render 'index'
      return
    end
  end

  def edit
    # find record with an id params
    @roles = Role.all
    @users = User.where(role_id: @roles.ids)
    @user = User.find_by_id(params[:id])

    unless @user
      flash[:error] = "User not found with an id ##{params[:id]}"
      redirect_to admin_users_path
      return
    end

    @user_method = "PATCH"
    @user_form_url = admin_user_path(@user.id)
  end

  # update department
  def update
    # find record with an id params
    @roles = Role.all
    @user = User.find_by_id(params[:id])

    unless @user
      flash[:error] = "User not found with an id ##{params[:id]}"
      redirect_to admin_users_path
      return
    end

    @user_method = "PATCH"
    @user_form_url = admin_user_path(@user.id)

    # if update record success
    if @user.update(user_without_password_params)
      flash[:success] = "User #{@user.name} had been updated successfully."
      redirect_to admin_users_path
      return
    else
      @error_messages = @user
      render 'edit'
      return
    end
  end

  def show
    # find record with an id params
    @user = User.find_by_id(params[:id])

    unless @user
      flash[:error] = "User not found with an id ##{params[:id]}"
      redirect_to admin_users_path
      return
    end
  end

  def destroy
    # find record with an id params
    @user = User.find_by_id(params[:id])

    unless @user
      flash[:error] = "User not found with an id ##{params[:id]}"
      redirect_to admin_users_path
      return
    end

    @user.destroy
    flash[:success] = "User with an id ##{params[:id]} has been deleted"
    redirect_to admin_users_path

  end

  private

  def user_without_password_params
    params.require(:user).permit(:email, :gender, :firstname, :lastname, :name, :role_id, :status)
  end

  def user_password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def user_params
    params.require(:user).permit(:email, :gender, :firstname, :lastname, :name, :password, :password_confirmation, :role_id, :status)
  end
end

app/controllers/my/users_controller.rb
class My::UsersController < ApplicationController
  before_action :authenticate_user!
  layout :my_layout

  def dashboard
    @alerted_stock = Stock.where(alerted: true, status: APP::ACTIVE)
    @alerted_count = @alerted_stock.count
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/my/users_helper.rb
module My::UsersHelper
end

app/views/admin/users/_form.html.slim
.row
  = form_for @user, html:{method: (@user_method.blank?) ? "POST" : @user_method, class: "frm-custom" , id: "user_frm_id"}, url: @user_form_url do |f|
    .col-sm-6
      .card.card-tasks
        - if @error_messages && @error_messages.errors.any?
          .card-header
            #message_wrapper
              = render 'share/error_messages'
        .card-body
          .form-group
            = f.label :firstname, for: 'user_username'
            = f.text_field :firstname, class: 'form-control', placeholder: 'Firstname', autofocus: true
          .form-group
            = f.label :lastname, for: 'user_username'
            = f.text_field :lastname, class: 'form-control', placeholder: 'Lastname', autofocus: true
          .form-group
            = f.label :email, for: 'user_email'
            = f.email_field :email, class: 'form-control', placeholder: 'Email'
          .form-group
            = f.label :password, for: 'user_password'
            = f.password_field :password, class: 'form-control', autocomplete: "off", placeholder: "Password"
          .form-group
            = f.label :password_confirmation, for: 'user_password_confirmation'
            = f.password_field :password_confirmation, class: 'form-control', autocomplete: "off", placeholder: "Password Confirmation"
          .form-group
            = f.label :gender, for: 'user_gender'
            = f.select :gender, options_for_select([[:male, APP::MALE],[:female, APP::FEMALE],[:other, APP::OTHER]], (@user and @user.gender) ? @user.gender : nil), {}, class: 'form-control'
          .form-group
            = f.label :role, for: "user_role_id"
            = f.select(:role_id, @roles.collect { |a| [a.name, a.id] }, {}, class: 'form-control')
          .form-group
            = f.label :status, for: "user_status"
            - if @user and @user.status == APP::BANNED
              - st = APP::USER_STATUS.dup
              - st.push({status: APP::BANNED}) if st.count <= 3
              = f.select :status, options_for_select(st.map { |st| [st[:status].capitalize, st[:status]] }, (@user and @user.status) ? @user.status : nil), {}, class: 'form-control'
            - else
              = f.select :status, options_for_select(APP::USER_STATUS.map { |st| [st[:status].capitalize, st[:status]] }, (@user and @user.status) ? @user.status : nil), {}, class: 'form-control'
          .form-group
            = link_to 'Cancel', admin_users_path, class: 'btn btn-default'
            span &nbsp;
            - if @edit_btn && @edit_btn == true
              = f.submit 'Update', class: 'btn btn-primary'
            - else
              = f.submit 'Save', class: 'btn btn-primary'

app/views/admin/users/_list-show.html.slim
h2.title User Detail
.row
  .col-sm-4
    .card.card-tasks
      .card-body
        .form-group
          label Firstname
          input.form-control name="stock_name" value = @user.firstname readonly=""
        .form-group
          label Lastname
          input.form-control name="stock_name" value = @user.lastname readonly=""
        .form-group
          label Username
          input.form-control name="stock_name" value = @user.name readonly=""
        .form-group
          label Email
          input.form-control name="stock_name" value = @user.email readonly=""
        .form-group
          label Gender
          input.form-control name="stock_name" value = @user.gender readonly=""
        .form-group
          label Role
          input.form-control name="stock_name" value = @user.role.name readonly=""
        .form-group
          label Status
          input.form-control name="stock_name" value = @user.status readonly=""

app/views/admin/users/_list.html.slim
tr
  td = @i += 1
  td 
    strong = @user.name.capitalize
  td = @user.email
  td = @user.gender.capitalize
  td = @user.role.name.capitalize
  td
    - if @user.status.blank?
      p -
    - else
      - if @user.status == APP::PENDING
        label.label.label-warning = @user.status.capitalize
      - elsif @user.status == APP::ACTIVE
        label.label.label-success = @user.status.capitalize
      - elsif @user.status == APP::INACTIVE
        label.label.label-info = @user.status.capitalize
      - else
        label.label.label-danger = @user.status.capitalize
  td
    ul class="list-inline"
      li = link_to "Edit", edit_admin_user_path(@user.id)
      li = link_to "Show", admin_user_path(@user.id)
      - unless @user.role.name == 'superadmin' and current_user.role.name != 'superadmin'
        li = link_to "Delete", admin_user_path(@user.id), method: :delete, data: { confirm: 'Are you sure?' }

app/views/admin/users/_no-password-form.html.slim
.row
  = form_for @user, html:{method: (@user_method.blank?) ? "POST" : @user_method, class: "frm-custom" , id: "user_frm_id"}, url: @user_form_url do |f|
    .col-sm-6
      .card.card-tasks
        .card-header
          - if @error_messages && @error_messages.errors.any?
            #message_wrapper
              = render 'share/error_messages'
          ul.nav.nav-tabs
            li.active
              a data-toggle="tab" href="#edit-user" Edit Profile
            li
              a data-toggle="tab" href="#edit-password" Change Password

        .tab-content
          .tab-pane.fade.card-body.in.active id="edit-user"
            .form-group
              = f.label :firstname, for: 'user_username'
              = f.text_field :firstname, class: 'form-control', placeholder: 'Firstname', autofocus: true
            .form-group
              = f.label :lastname, for: 'user_username'
              = f.text_field :lastname, class: 'form-control', placeholder: 'Lastname', autofocus: true
            .form-group
              = f.label :email, for: 'user_email'
              = f.email_field :email, class: 'form-control', placeholder: 'Email'
            .form-group
              = f.label :gender, for: 'user_gender'
              = f.select :gender, options_for_select([[:male, APP::MALE],[:female, APP::FEMALE],[:other, APP::OTHER]], (@user and @user.gender) ? @user.gender : nil), {}, class: 'form-control'
            .form-group
              = f.label :role, for: "user_role_id"
              = f.select(:role_id, @roles.collect { |a| [a.name, a.id] }, {}, class: 'form-control')
            .form-group
              = f.label :status, for: "user_status"
              - if @user and @user.status == APP::BANNED
                - st = APP::USER_STATUS.dup
                - st.push({status: APP::BANNED}) if st.count <= 3
                = f.select :status, options_for_select(st.map { |st| [st[:status].capitalize, st[:status]] }, (@user and @user.status) ? @user.status : nil), {}, class: 'form-control'
              - else
                = f.select :status, options_for_select(APP::USER_STATUS.map { |st| [st[:status].capitalize, st[:status]] }, (@user and @user.status) ? @user.status : nil), {}, class: 'form-control'
            .form-group
              = link_to 'Cancel', admin_users_path, class: 'btn btn-default'
              span &nbsp;
              - if @edit_btn && @edit_btn == true
                = f.submit 'Update', class: 'btn btn-primary'
              - else
                = f.submit 'Save', class: 'btn btn-primary'
            
          .tab-pane.fade.card-body id="edit-password"
            .form-group
              = f.label :password, for: 'user_password'
              = f.password_field :password, class: 'form-control', autocomplete: "off", placeholder: "Password"
            .form-group
              = f.label :password_confirmation, for: 'user_password_confirmation'
              = f.password_field :password_confirmation, class: 'form-control', autocomplete: "off", placeholder: "Password Confirmation"
            .form-group
              = link_to 'Cancel', admin_users_path, class: 'btn btn-default'
              span &nbsp;
              - if @edit_btn && @edit_btn == true
                = f.submit 'Update', class: 'btn btn-primary'
              - else
                = f.submit 'Save', class: 'btn btn-primary'

app/views/admin/users/dashboard.html.slim
.row
  .col-sm-3
    - unless @alerted_count.blank? or @alerted_count == 0
      .card.card-stats
        .card-body
          .row
            .col-sm-5
              i.fa.fa-close.fa-danger
            .col-sm-7.text-right
              - unless @alerted_count.blank? or @alerted_count == 0
                span.text-danger 
                  strong #{@alerted_count} alerted!
                  br
                  | Please check your Stocks!
        .card-footer
          hr
          i.fa.fa-repeat
          = link_to 'Update now', admin_stocks_path, class: "notify"
  / - else
  /   .section-wrapper
  /     p We don't have any braches yet!

app/views/admin/users/edit.html.slim
- @edit_btn = true
= render 'no-password-form'

app/views/admin/users/index.html.slim
.row
  .col-sm-6
    = link_to "Add New", new_admin_user_path, :class => "btn btn-primary btn-btmar"
  .col-sm-6
    .input-group
      - if (@filter_param && @filter_param != "")
        = hidden_field_tag(:filter, @filter_param, class: 'form-control')
      = text_field_tag(:query, (@query_param && @query_param != "") ? @query_param : nil, list: "option_selected_datalist", placeholder: "Search...", autofocus: true, class: 'form-control', id: 'stock_select_type_input')
      .input-group-btn
        = submit_tag("Search", name: "submit", class: 'btn btn-default')

.row
  .col-sm-12
    .card.card-tasks
      .card-body
        - unless @users.blank?
          table.table
            thead
              tr
                th #
                th Username
                th Email
                th Gender
                th Role
                th Status
                th Action
            tbody
              - @i = 0
              - for @user in @users
                = render 'list'
        - else
          .section-wrapper
            p We don't have any users yet!

app/views/admin/users/new.html.slim
= render 'form'

app/views/admin/users/show.html.slim
= render 'list-show'